### ISSUE TITLE
[Android] Error while updating property reactStyle

### ISSUE THREAD

**Issue by RevanScript** [react-native-mapbox/maps#10]
Hello!

I've got a problem on Android when updating iconRotate style dynamically. Is this a bug or I can fix it somehow?

```tsx
<MapboxGL.ShapeSource
    id="symbolLocationSource"
    shape={this.route.coordinate}
>
    <MapboxGL.Animated.SymbolLayer
        id="symbolLocationSymbols"
        minZoomLevel={1}
        style={[styles.icon, { iconRotate: this.rotationValue }]}
    />
</MapboxGL.ShapeSource>

...

const styles = MapboxGL.StyleSheet.create({
    icon: {
        iconImage: require('assets/images/test@x1.png'),
        iconAllowOverlap: true,
        iconSize: 1,
    },
});
```

![Screenshot_1556449415](https://user-images.githubusercontent.com/5047628/56863391-79d1b500-69be-11e9-9ebe-4e0776350e95.png)

This code works if iconRotate value is not changing

**Versions (please complete the following information):**
 - Platfrom: Android
 - React Native Version [e.g. 0.59.1]

**Comment by whiteHatCip** [comment]
It is probably saying that you are passing a string value to the style property iconrotate, but the value is supposed to be a double, and the OS is saying that you are trying to cast that string value to the expected double.
