### ISSUE TITLE
Post-Expressions Update: Initial Map Zoom and Coords Not Correct

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox/maps#13]
**Describe the bug**
Initial Map Zoom and Coords Not Correct
Reference #4 

**To Reproduce**
With newest expression merged on master installed, load map with initial center and coordinates defined:

```
      <Mapbox.MapView
        zoomLevel={8}
        centerCoordinate={[-111.8678, 40.2866]}
        style={styles.map}
        showUserLocation={true}
>
```

**Expected behavior**
Map zoom/center coords should load initially as before.

**Screenshots**
Resulting map regardless of center/coords defined:

<img width="584" alt="Screen Shot 2019-04-30 at 4 30 53 PM" src="https://user-images.githubusercontent.com/894983/56998441-88f46680-6b68-11e9-879b-770227593d3a.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Simulator Xr
 - React Native Version 0.59

**Additional context**

A big thank you and shoutout to @mfazekas for the recent expressions updates.  The good news is we have the newest custom maps in Mapbox Studio working and displaying:

<img width="584" alt="Screen Shot 2019-04-30 at 4 48 52 PM" src="https://user-images.githubusercontent.com/894983/56998490-b6d9ab00-6b68-11e9-82ec-cf9b71c70303.png">

**Comment by mfazekas** [comment]
@systemlevel thanks for trying out the new branch.

We need a doc update/rewrite, on how to migrate code for the new mapbox.

As mentioned in https://github.com/react-native-mapbox/maps/pull/4#issue-270304205 

```jsx
<Mapbox.MapView
        zoomLevel={8}
        centerCoordinate={[-111.8678, 40.2866]}
        style={styles.map}
        showUserLocation={true}
...
<Mapbox.MapView>
```

is now
````jsx
<Mapbox.MapView
        style={styles.map}
        
>
    <Mapbox.Camera
       zoomLevel={8}
        centerCoordinate={[-111.8678, 40.2866]}
     />
    <Mapbox.UserLocation 
         showUserLocation={true}
     />
...
</Mapbox.MapVIew>
```

**Comment by systemlevel** [comment]
@mfazekas Thank you!  'll work on some doc updates to reflect these changes as well.

**Comment by systemlevel** [comment]
@mfazekas getting an issue with RCTMGLCamera after installing react-native-mapbox/maps on another machine and running the app.  Is this related to the above changes?

<img width="1052" alt="Screen Shot 2019-04-30 at 10 25 03 PM" src="https://user-images.githubusercontent.com/894983/57005659-fb7c3b00-6b96-11e9-9709-37e2267dcf7d.png">

**Comment by mfazekas** [comment]
RCTMGLCamera should be in the project, generated by cocoapods. Are you using the workspace to build?

![kép](https://user-images.githubusercontent.com/52435/57006647-a1a16280-6be2-11e9-87bf-c52ee8aced82.png)

**Comment by systemlevel** [comment]
> RCTMGLCamera should be in the project, generated by cocoapods. Are you using the workspace to build?
> 
> ![kép](https://user-images.githubusercontent.com/52435/57006647-a1a16280-6be2-11e9-87bf-c52ee8aced82.png)

@mfazekas I have tried running it with react-native run-ios in the terminal as well as in xcode by building and running it there.  If I misunderstood your question let me know. 

Both of those approaches result in a failed build:

```
info Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTMGLCamera", referenced from:

info       objc-class-ref in libRCTMGL.a(RCTMGLMapView.o)

info ld: symbol(s) not found for architecture x86_64

info clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm attempted to clear out node_modules and do a clean npm install but the same error results still.

**Comment by mfazekas** [comment]
@systemlevel sorry i thought you're using cocapods, but it appears you're not.
Does your RCTMGL.xcodeproj contains the RCTMLCamera?
![kép](https://user-images.githubusercontent.com/52435/57030179-35efe180-6c44-11e9-8a55-a1d5e20c244e.png)

It did for a project i've started with 
```sh
react-native init
npm install react-native-mapbox/maps --save 
react-native link
# add Mapbox.framework to the project
```
it builds/run fine, it's also in the github project, so not sure how your version has it missing.

https://github.com/react-native-mapbox/maps/blob/3c24cbb76ce81c1972dbd7727c44d5ab0b47bd8c/ios/RCTMGL.xcodeproj/project.pbxproj#L27-L28

**Comment by systemlevel** [comment]
@mfazekas Yes I see that as well. So strange...  I ended up deleting my project and then pulling a fresh copy down from my git repository and everything started working.  I wish I knew what the exact issue was but I could't determine why that happened. 

Things are working now after installing everything again from a clean clone of our repo. 

Thanks again for your help.

**Comment by systemlevel** [comment]
All issues have been addressed and updated docs to follow. Closing this out for now...
