### ISSUE TITLE
Blue Dot Representing User Location Missing

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox/maps#17]
**Describe the bug**
User location indicated by blue dot not showing on maps.

**To Reproduce**
Have tried the following including the new UserLocation object:

```
      <Mapbox.MapView
        style={styles.map}
        showUserLocation={true}
      >
```

```
        <Mapbox.UserLocation 
            showUserLocation={true}
        />

```

**Expected behavior**

Blue dot:
<img width="441" alt="Screen Shot 2019-05-02 at 12 32 57 AM" src="https://user-images.githubusercontent.com/894983/57059303-e7f1d280-6c71-11e9-94a5-224ed012d6b3.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone Xs and Simulator
 - React Native Version 0.59

**Additional context**
Possible post-expressions update impact @mfazekas.  Let me know if I have anything wrong in my attempt at showUserLocation based on the new changes from your vantage point.

**Comment by alexiri** [comment]
Looking at the [code](https://github.com/react-native-mapbox/maps/blob/master/javascript/components/UserLocation.js#L62), I think you might need `visible={true}` instead. Still, that code looks like it's not quite finished, for example there's no way to specify the `TrackingMode`.

**Comment by mfazekas** [comment]
@alexiri @systemlevel 
yes 
`Mapview#showUserLocation` is now `UserLocation#visible`
tracking mode can be specified in the camera so `Mapview#userTrackingMode` is now `Camera#userTrackingMode: enum {'normal','compass','course'}` and `Camera#followUserLocation: bool`

**Comment by systemlevel** [comment]
@alexiri @mfazekas Perfect.  These two objects were necessary to get the users location showing on the map:

```
        <Mapbox.UserLocation 
          visible={true}
        />
```

and

```
        <Mapbox.Camera
          zoomLevel={12}
          followUserLocation={true} 
        />
```

Once you get the hang of new UserLocation and Camera objects the logic makes a lot of sense to me and how these are used.

**Comment by kristfal** [comment]
Looks solved, closing. We'll need to write a migration guide, but that should be covered in a different issue.

**Comment by club9822** [comment]
Have a strange situation. Sometimes user location not shows. Gps and network is open befor app launch .no user marker shows. By closing app, and opening, shows.it happens In android, release and debug, real device and genymotion. Samsung s7 s5. huawei y5 asus real device

**Comment by nasmuris** [comment]
Native SDKs make it possible to show current user location heading [via renderMode- android](https://docs.mapbox.com/android/maps/overview/location-component/#rendermode) or [showsUserHeadingIndicator - iOS](https://docs.mapbox.com/ios/api/maps/5.0.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)showsUserHeadingIndicator)
Why is not this supported and JS implementation is used?

**Comment by mfazekas** [comment]
@nasmuris the js implemenation has the advantage of customization, you can use your own location component. Ideally we'd have an option to use the native current location components.

**Comment by sauhardar** [comment]
@mfazekas, how is a custom location component used to display the user's location and direction?

**Comment by ferdicus** [comment]
@sauhardar, pass in for example a `SymbolLayer` with an image source of your choosing and it will get rendered instead of the blue dot
