### ISSUE TITLE
Map Center Offset?

### ISSUE THREAD

**Issue by timhilgenstoehler** [react-native-mapbox/maps#21]
Hello, 

is it possible to offset the center of the map? My map has 100vw and 100vh dimensions but I have a slider 1/3 of vh on top of the map. Can i center the map inside the first 2/3 of vh instead of the whole screen?

Kind Regards,
Tim

**Comment by kristfal** [comment]
Yes, you can use padding with setCamera to offset any setCamera action with pixel padding.

**Comment by timhilgenstoehler** [comment]
`this.map.setCamera({
        centerCoordinate: [this.state.places[0].lng, this.state.places[0].lat],
        zoom: 14,
        paddingTop: 500,
        duration: 500,
      });`

is not working sadly. I didn't find anything else in the docs. How can I achieve this? I really appreciate
your work for this repository!

**Comment by kristfal** [comment]
You need to use bounding box camera operations iirc to make padding work. At least it worked on 6.1.4.

**Comment by timhilgenstoehler** [comment]
```
const visibleBounds = await this.map.getVisibleBounds();
this.map.fitBounds(visibleBounds[0],visibleBounds[1],[100,0,0,0], 1000)
```

Thanks a lot but this is still not working as expected. Its making padding on the top but aswell on the side. I can position my initial markers with:

```
contentInset={[100, 0, 0, 0]}
```

Is there a possibility to animate these values somehow? Like a <Animated.MapboxGL.MapView /> ?
