### ISSUE TITLE
Repeated requests for sprite sheet

### ISSUE THREAD

**Issue by gmaclennan** [react-native-mapbox/maps#22]
I'm kicking the tires with the new changes in master @ 79a4e56bba93df87985bb953d5c2ae90861816dc. I came across this minor issue with repeated network requests.

**Describe the bug**
I am seeing repeated requests approx. every second for the style spritesheet files:

- `sprite@2x.png`
- `sprite@2x.json`

I am also seeing this for font (pbf) resources.

I am not seeing any repeat requests for other style resources (e.g. the main style.json is only being requested once, and the tiles are only being requested once). The `RCTMGLMapView` component is only being rendered once too, so this does not seem to be an issue with render being called multiple times.

I tried removing `<MapboxGL.UserLocation showUserLocation={true} />` in case it was location updates that was causing the sprite requests, but I still see the requests when it is removed.

I have tried turning off GPS in case the GPS updates were triggering a re-request of these resources, but I still see the requests.

**To Reproduce**
Add a custom style, monitor the network requests

**Expected behavior**
The resources in the stylesheet (sprites and font files) should only be loaded once.

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Moto X4
 - SDK Version 28
 - React Native Version 0.58.5

**Additional context**
I am serving a custom style locally, which is how I can see the network requests. I am serving the sprite and font resources with `cache-control: no-cache` headers, which may be relevant?

**Comment by alexiri** [comment]
@gmaclennan could you share the code you're using? It might make it easier to reproduce this issue, but mostly it might help me figure out how to set up a custom local style on the new version. :D I have it working on the old version, but for some reason the map doesn't load with this new one. We could also add it to the example app, to help others in the future.

**Comment by kristfal** [comment]
`cache-control: no-cache` is very likely the culprit. The native SDKs respects cache headers across all resources as far as I recall. I propose you change this and retry.

**Comment by gmaclennan** [comment]
Thanks @kristfal after a bit more testing I can confirm that `cache-control: no-cache` causes the native SDK to repeatedly request the resources every second (despite no map interaction). It actually re-requests all the font and style resources every `n` seconds where `cache-control: max-age=n`. I wouldn't expect that behaviour, but it's not really an issue for us.

@alexiri the frontend code we are using is here https://github.com/digidem/mapeo-mobile but all that is doing is passing a localhost URL to the MapView for the style.json. The style resources are served by a local http server we run in a node process on the phone. The code for serving the style file, font resources and tiles is here:

https://github.com/digidem/mapeo-server/blob/master/api.js#L251

**Comment by alexiri** [comment]
@gmaclennan thanks! Slightly different usecase than us, I guess, we're reading the files directly as assets.
