### ISSUE TITLE
'rasterResampling' is unavailable: Use rasterResamplingMode instead.

### ISSUE THREAD

**Issue by HPieters** [react-native-mapbox/maps#37]
**Describe the bug**
When trying to build the latest version of @react-native-mapbox/maps in Xcode I get a "Semantic Issue" in [RCTMGLStyle.m line 1470](https://github.com/react-native-mapbox/maps/blob/master/ios/RCTMGL/RCTMGLStyle.m#L1470) 'rasterResampling' is unavailable: Use rasterResamplingMode instead.

**To Reproduce**
Create a clean React Native project with react-native init. Use pod installation. Try to build and run the project using <project>.xcworkspace.

**Expected behavior**
I expected my React Native app to build without errors.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Simulator
 - OS: 12.2
 - SDK Version: Latest
 - React Native Version: Latest

**Screenshot**
![Screenshot 2019-05-10 at 14 32 43](https://user-images.githubusercontent.com/2362116/57527685-9c55bd80-7330-11e9-894d-6354c305b05c.png)

**Possible solution**
The proposed solution seems to be the suggestion of XCode, renaming rasterResampling to rasterResamplingMode.

**Comment by kristfal** [comment]
Reopen if issue still exists in master.
