### ISSUE TITLE
Crash in "Indoor Building Map" in example app

### ISSUE THREAD

**Issue by alexiri** [react-native-mapbox/maps#49]
**Describe the bug**
The app crashes with the following stacktrace when running the "Indoor Building Map" example:

```
05-18 19:28:15.697  3444  3444 E AndroidRuntime: FATAL EXCEPTION: main
05-18 19:28:15.697  3444  3444 E AndroidRuntime: Process: com.rnmapboxglexample, PID: 3444
05-18 19:28:15.697  3444  3444 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.style.light.Light com.mapbox.mapboxsdk.maps.Style.getLight()' on a null object reference
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.rctmgl.components.styles.light.RCTMGLLight.addToMap(RCTMGLLight.java:33)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onMapReady(RCTMGLMapView.java:373)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1154)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1140)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:207)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:61)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:321)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-18 19:28:15.697  3444  3444 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Versions:**
 - Platfrom: Android
 - Device: Oneplus 3T
 - OS: 8.0.0
 - SDK Version: 28
 - React Native Version: 0.59.0

**Comment by alexiri** [comment]
I'm still getting the same crash, which is weird. I'm not sure if I'm even using the latest code. I did a `./gradlew clean`, deleted the `node_modules` folder, deleted the react-native-mapbox-maps-7.0.0.tgz file, and ran `yarn cache clean && yarn install`. What am I missing?

**Comment by mfazekas** [comment]
@alexiri is this the same crash with same stacktrace? 
```
at com.mapbox.rctmgl.components.styles.light.RCTMGLLight.addToMap(RCTMGLLight.java:33)
```

Can you verify that RCTMGLLight.java in `example/node_modules/@react-native-mapbox/maps` looks like this:

https://github.com/react-native-mapbox/maps/blob/8835e678c1a1d1232e9c47c7fb00c89377dcabc7/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/light/RCTMGLLight.java#L32-L35

**Comment by alexiri** [comment]
Yes, the stack trace is the same, but I see your changes in RCTMGLLight.java, that's why I'm so confused. I also uninstalled the app from my device, but same thing.

**Comment by mfazekas** [comment]
@alexiri must be some outdated binary. As with the changes line 33 in RCTMGLLight.java has no getLight any more. 

Can try to remove example/android/build and example/android/app/build.

You can also try `gradlew cleanBuildCache` and you can add some syntax error to RCTMGLLight.java to make sure it's built.

**Comment by alexiri** [comment]
Ah, `gradlew cleanBuildCache` did the trick, thanks! I confirm it works now.
