### ISSUE TITLE
[Discussion] Emulator Performance With Maps

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox/maps#58]
When we run our react-native-mapbox/maps the performance on the maps running on the iOS emulators is very slow in most cases.  The actual devices run great.  Are there any emulators the community is using that tends to work better with the newest maps from mapbox?  Perhaps we are the only ones experiencing slow performance on the xcode emulators?

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Xcode Emulators
 - React Native Version 0.59

**Comment by systemlevel** [comment]
As a follow up to this what we have done is created two versions of our map.  One version is the full version and the other is very stripped down without many vector features. This helps the performance on the iOS emulators.  Not ideal but I don't see any way to improve the emulator situation at the moment.

**Comment by kristfal** [comment]
Nothing we can do on this side of the repo. Rendering is handled upstream in mapbox-gl-native. Your workaround seems decent through. Closing.
