### ISSUE TITLE
RasterSource layer not displaying

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox/maps#6]
**Describe the bug**

Library does not display raster source layers that contain a token in URL?

**To Reproduce**

Simply add a raster source layer that contains a token in the URL

**Expected behavior**

The raster source layer should display correctly just like the one in the exmaple:

```
      const rasterSourceProps = {
        id: 'stamenWatercolorSource',
        url: 'https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg',
        tileSize: 256,
      };
```
With the stamen watercolor raster source defined it works just fine.

```
              <Mapbox.MapView
                zoomLevel={16}
                centerCoordinate={[-122.400021, 37.789085]}
                style={sheet.matchParent}
              >
                <Mapbox.RasterSource {...rasterSourceProps}>
                  <Mapbox.RasterLayer
                    id="stamenWatercolorLayer"
                    sourceID="stamenWatercolorSource"
                    style={{rasterOpacity: .5}}
                  />
                </Mapbox.RasterSource>
              </Mapbox.MapView>
```

To see bug add a raster source layer that has a token.  Example:

      const rasterSourceProps = {
        id: 'stamenWatercolorSource',
        url: 'https://mapserver.neotreks.com/arcgis/rest/services/NeoTreks/LandCover/MapServer/tile/{z}/{y}/{x}?token=' + this.context.state.tokenNeoTreks,
        tileSize: 256,
      };

**Screenshots**

Watercolor raster source layer loads fine:
<img width="529" alt="Screen Shot 2019-04-20 at 12 54 44 PM" src="https://user-images.githubusercontent.com/894983/56461511-942de200-6371-11e9-91a1-d00b0175ec9f.png">

Neotreks basemap does not load at all. Just left with default street view:
<img width="545" alt="Screen Shot 2019-04-20 at 1 23 55 PM" src="https://user-images.githubusercontent.com/894983/56461513-9bed8680-6371-11e9-8ef8-9bc04e8614d4.png">

react-native-maps has no issue loading Neotreks basemap raster layer. Screenshot of neotreks raster layer loading in react-native-maps library:
<img width="543" alt="Screen Shot 2019-04-20 at 1 27 54 PM" src="https://user-images.githubusercontent.com/894983/56461523-b293dd80-6371-11e9-890c-6556d068a3d9.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Simulator
 - React Native Version 0.59.5

**Additional context**
As noted previously this raster layer loads just fine in react-native-maps.  It's not clear why this layer does not load as a raster layer in react-native-mapbox-gl

react-native-maps has no issue loading Neotreks basemap raster layer. Screenshot of neotreks raster layer loading in react-native-maps library:
<img width="543" alt="Screen Shot 2019-04-20 at 1 27 54 PM" src="https://user-images.githubusercontent.com/894983/56461523-b293dd80-6371-11e9-890c-6556d068a3d9.png">

**Comment by systemlevel** [comment]
@kristfal Do you guys have any quick insights into why this behavior might be happening?  It's been difficult to understand why the neotreks layer won't load but the watercolor layer will. Is there an insight into this you may have?  Thanks so much. @nitaliano

**Comment by systemlevel** [comment]
Figured out how to make this work with react-native-mapbox-gl.  It's working now.  Had create a finished loading state to make sure the async call to the token generator was completely finished before attempting to display the RasterSource and RasterLayer.

**Comment by arnaudambro** [comment]
@systemlevel thanks for your post, you solved a problem of mine ! but I still have an issue: I see you put a prop `style={{rasterOpacity: .5}}` on the `Mapbox.RasterLayer`, I want to put the opacity to 1 but it hide the `Mapbox.ShapeSource` I also put on the map.
Do you know how to display a ShapeSource _above_ the `RasterLayer` ?

**Comment by manarfalah** [comment]
@systemlevel 

> Figured out how to make this work with react-native-mapbox-gl. It's working now. Had create a finished loading state to make sure the async call to the token generator was completely finished before attempting to display the RasterSource and RasterLayer.

can you please share your code ? facing the same issue and not able to fix it
