### ISSUE TITLE
[Android] isUserInteraction in onRegionDidChange is incorrectly set to false

### ISSUE THREAD

**Issue by Darkilen** [react-native-mapbox/maps#63]
**Describe the bug**
After updating `zoomLevel` or `centerCoordinate` in `MapboxGL.Camera` object, the next manual move triggers `onRegionDidChange` with `isUserInteraction` set to `false` instead of `true`

**To Reproduce**
- Bind `onRegionDidChange` and log his `features` parameter
- Update `zoomLevel` or `centerCoordinate`
- Manually move the map

**Expected behavior**
`isUserInteraction` must be set to `true`

##### Second bug which should be related
Updating `zoomLevel` or `centerCoordinate` must trigger `onRegionDidChange` with `isUserInteraction` set to `false` (actually `onRegionDidChange` is not triggered in this cases)

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Physical device, Xiaomi redmi note 5
 - OS: 8.1.0
 - SDK Version: 28
 - React Native Version 0.59.8

**Comment by mfazekas** [comment]
@Darkilen thanks for the report, i was able to repro on android  (ios seems to work fine)
Is this a regression? I think it happens with the repo or 6.* version too.

I think this commit is the culprit, it tries to detect fling animation, but it seems to be in effect even if it's nothing to do with that:

https://github.com/nitaliano/react-native-mapbox-gl/commit/2bc9841b443f8214e7c9f9c9357a6b8d37d32aaf
